### ISSUE TITLE
upgrade to nuxt.js 1.0

### ISSUE THREAD

**Issue by phlogisticfugu** [phlogisticfugu/perfect-paca#5]
nuxt.js (which this relies upon) just released version 1.0

to upgrade this package to use that as a dependency

**Comment by afifsohaili** [comment]
hey, thanks for this effort. let me know what I can help with ;)

**Comment by LoneRifle** [comment]
In case you haven't already gotten there.... Here's what I've learnt so far:
In order to get nuxt 1.0 to play nicely with node 6.10, nuxt.config.js has to be modified so that `build` overrides the default babel presets as follows:
```js
  // const IS_LAMBDA = process.env.AWS_EXECUTION_ENV === 'nodejs6.10'
    babel: {
      presets: ({ isServer }) => [
        [
          require.resolve('babel-preset-vue-app'),
          { targets: isServer ? { node: IS_LAMBDA ? '6.10.0' : '8.0.0' } : { ie: 9, uglify: true } }
        ]
      ]
    },
```
We also need to provide some node 8 features through various shims, and use babel-register to transpile nuxt on the fly as follows:
```js
const util = require('util')
if (!util.promisify) {
  require('util.promisify/shim')()
}
if (!Object.values) {
  require('object.values').shim()
}
if (process.env.AWS_EXECUTION_ENV === 'nodejs6.10') {
  require('babel-register')({
    only: /nuxt\/lib/,
    presets: [
      [ 'env', { targets: { node: 'current' } } ],
    ],
  })
}
```
including the above as a module would allow you to easily bring it in as a node `-r` arg, so that you can invoke nuxt with something like `node -r ./util/node-8-backcompat node_modules/.bin/nuxt build`

babel-register is a nuxt dependency, so only object.values and util.promisify have to be explicitly brought in

**Comment by phlogisticfugu** [comment]
Thanks @LoneRifle 

Actually, I've been pretty slammed and haven't gotten to really dig properly into this.  @afifsohaili if you could put in a PR, that'd be awesome!
